### ISSUE TITLE
Request for a few primary keybindings

### ISSUE THREAD

**Issue by dit7ya** [chenyanming/spacemacs_module_for_doom#3]
Hi, thank you for this package, it has made my switching to doom much easier. However, I would like to have these few basic keybindings (I use these very very often).

- `SPC TAB` for switch to last buffer.
- `SPC c l` for comment line (and the entire comments related kbds)
- `,` for major mode keybindings
- `SPC SPC` for `M-x`

Also, `SPC w` commands mess things when there is a sidebar buffer open.

**Comment by chenyanming** [comment]
Hi @dit7ya 

Thanks for your feedback. Here some notes:

1. `SPC TAB` is workspace keybinding that doom original good feature, you can use `SPC TAB` as prefix to switch workspace. In spacemacs, you can use `SPC-l` t swtich the layout, they are same idea. It is better to keep it. Since this package does not completely replace doom with spacemacs keybindings. It combines both the goodies of doom and spacemacs. 

2. For `SPC c l`, I just updated spacemacs-evil layer 760753d.

3. What major mode keybindings do you need specificly? We need to add it individually and test them properly, and porting all major modes from spacemacs needs too much work. 

4. I avoid to use `map!` in this package However, for `SPC SPC`, porting with `map!` is easier to port in original spacemacs way at this moment. Check the update 99a99c8.

**Comment by dit7ya** [comment]
Can we not just have `,` as an alias for `SPC m` so that it works for any and all major modes?

Thanks for the updates.

**Comment by chenyanming** [comment]
Hi @dit7ya, for this issue, I think it is easier to set doom's `doom-localleader-key` as `,`
```
(setq doom-leader-key "SPC"
      doom-leader-alt-key "C-SPC"
      doom-localleader-key ",")
```
Before the perfect solution, I suggest you add the setting into `config.el` just like me, since there are too many major modes out there, I do not know if it perfectly work. Actually, I normally use `,` instead `SPC-m`, I think it should be ok.

**Comment by chenyanming** [comment]
Besides, what senario does this refer to
`Also, SPC w commands mess things when there is a sidebar buffer open.`

what sidebar do you use? I just use `treemacs`, I think it is working alright.
